// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: flpower

#include "../ui.h"

void ui_SM_Screen_screen_init(void)
{
ui_SM_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SM_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SM_PanelLogo = lv_obj_create(ui_SM_Screen);
lv_obj_set_width( ui_SM_PanelLogo, 200);
lv_obj_set_height( ui_SM_PanelLogo, 50);
lv_obj_set_align( ui_SM_PanelLogo, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SM_PanelLogo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SM_PanelLogo, lv_color_hex(0x2D2E2E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SM_PanelLogo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SM_PanelLogo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_SM_PanelLogo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SM_LabelLogo1 = lv_label_create(ui_SM_PanelLogo);
lv_obj_set_width( ui_SM_LabelLogo1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SM_LabelLogo1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SM_LabelLogo1, 30 );
lv_obj_set_y( ui_SM_LabelLogo1, 0 );
lv_obj_set_align( ui_SM_LabelLogo1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SM_LabelLogo1,"POWER");
lv_obj_set_style_text_font(ui_SM_LabelLogo1, &ui_font_Font40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SM_LabelLogo2 = lv_label_create(ui_SM_PanelLogo);
lv_obj_set_width( ui_SM_LabelLogo2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SM_LabelLogo2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SM_LabelLogo2, -65 );
lv_obj_set_y( ui_SM_LabelLogo2, 0 );
lv_obj_set_align( ui_SM_LabelLogo2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SM_LabelLogo2,"FL");
lv_obj_set_style_text_color(ui_SM_LabelLogo2, lv_color_hex(0xC41414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SM_LabelLogo2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SM_LabelLogo2, &ui_font_Font40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SM_Screen, ui_event_SM_Screen, LV_EVENT_ALL, NULL);

}
