// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: flpower

#include "gui.h"

void sp_screen_in(lv_event_t * e)
{
	// Your code here
    gui_screen_id = Screen_SP_ID;
    gui_sp_value_select(0);
    gui_sp_value_step_select(0);
    gui_sp_set_refresh();
    gui_sp_power_select_refresh();
}
